version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/app/data
    networks:
      - app-net

  backend1:
    build: .
    environment:
      - SERVER_ID=1
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - ACCESS_EXPIRES_IN=${ACCESS_EXPIRES_IN}
      - REFRESH_EXPIRES_IN=${REFRESH_EXPIRES_IN}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_SUBJECT=${VAPID_SUBJECT}
      - NODE_ENV=production
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
    networks:
      - app-net

  backend2:
    build: .
    environment:
      - SERVER_ID=2
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - ACCESS_EXPIRES_IN=${ACCESS_EXPIRES_IN}
      - REFRESH_EXPIRES_IN=${REFRESH_EXPIRES_IN}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_SUBJECT=${VAPID_SUBJECT}
      - NODE_ENV=production
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
    networks:
      - app-net

  backend3:
    build: .
    environment:
      - SERVER_ID=3
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - ACCESS_EXPIRES_IN=${ACCESS_EXPIRES_IN}
      - REFRESH_EXPIRES_IN=${REFRESH_EXPIRES_IN}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_SUBJECT=${VAPID_SUBJECT}
      - NODE_ENV=production
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d        # <-- именно эта папка
      - ./certs:/etc/nginx/certs:ro  
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - app-net

networks:
  app-net:
volumes:
  pgdata: